// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_NATIVE_VIDEO_API_G_H_
#define PIGEON_NATIVE_VIDEO_API_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>



// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class NativeVideoHostApi;
  friend class NativeVideoFlutterApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};



// Frame info from video stream header
//
// Generated class from Pigeon that represents data sent in messages.
class FrameInfo {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit FrameInfo(int64_t frame_count);

  // Constructs an object setting all fields.
  explicit FrameInfo(
    const std::string* cam_idx,
    const std::string* cam_num,
    const double* brightness,
    const bool* motion,
    int64_t frame_count);

  const std::string* cam_idx() const;
  void set_cam_idx(const std::string_view* value_arg);
  void set_cam_idx(std::string_view value_arg);

  const std::string* cam_num() const;
  void set_cam_num(const std::string_view* value_arg);
  void set_cam_num(std::string_view value_arg);

  const double* brightness() const;
  void set_brightness(const double* value_arg);
  void set_brightness(double value_arg);

  const bool* motion() const;
  void set_motion(const bool* value_arg);
  void set_motion(bool value_arg);

  int64_t frame_count() const;
  void set_frame_count(int64_t value_arg);


 private:
  static FrameInfo FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class NativeVideoHostApi;
  friend class NativeVideoFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> cam_idx_;
  std::optional<std::string> cam_num_;
  std::optional<double> brightness_;
  std::optional<bool> motion_;
  int64_t frame_count_;

};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Host API - called from Dart, implemented in C++
//
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class NativeVideoHostApi {
 public:
  NativeVideoHostApi(const NativeVideoHostApi&) = delete;
  NativeVideoHostApi& operator=(const NativeVideoHostApi&) = delete;
  virtual ~NativeVideoHostApi() {}
  // Initialize renderer and return textureId
  virtual ErrorOr<int64_t> Initialize(int64_t texture_key) = 0;
  // Start ZMQ stream for specific texture
  virtual std::optional<FlutterError> StartStream(
    int64_t texture_key,
    const std::string& zmq_address) = 0;
  // Stop ZMQ stream for specific texture
  virtual std::optional<FlutterError> StopStream(int64_t texture_key) = 0;
  // Get current frame info (for polling)
  virtual ErrorOr<std::optional<FrameInfo>> GetFrameInfo(int64_t texture_key) = 0;
  // Dispose resources for specific texture
  virtual std::optional<FlutterError> Dispose(int64_t texture_key) = 0;

  // The codec used by NativeVideoHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `NativeVideoHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    NativeVideoHostApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    NativeVideoHostApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  NativeVideoHostApi() = default;

};
// Flutter API - called from C++, implemented in Dart
//
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class NativeVideoFlutterApi {
 public:
  NativeVideoFlutterApi(flutter::BinaryMessenger* binary_messenger);
  NativeVideoFlutterApi(
    flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const flutter::StandardMessageCodec& GetCodec();
  // Frame received callback with header info
  void OnFrameReceived(
    const FrameInfo& info,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  // Error callback
  void OnError(
    const std::string& message,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);

 private:
  flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

#endif  // PIGEON_NATIVE_VIDEO_API_G_H_
