// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "native_video_api.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

// FrameInfo

FrameInfo::FrameInfo(int64_t frame_count)
 : frame_count_(frame_count) {}

FrameInfo::FrameInfo(
  const std::string* cam_idx,
  const std::string* cam_num,
  const double* brightness,
  const bool* motion,
  const int64_t* bbox_x,
  const int64_t* bbox_y,
  const int64_t* bbox_w,
  const int64_t* bbox_h,
  const int64_t* width,
  const int64_t* height,
  int64_t frame_count)
 : cam_idx_(cam_idx ? std::optional<std::string>(*cam_idx) : std::nullopt),
    cam_num_(cam_num ? std::optional<std::string>(*cam_num) : std::nullopt),
    brightness_(brightness ? std::optional<double>(*brightness) : std::nullopt),
    motion_(motion ? std::optional<bool>(*motion) : std::nullopt),
    bbox_x_(bbox_x ? std::optional<int64_t>(*bbox_x) : std::nullopt),
    bbox_y_(bbox_y ? std::optional<int64_t>(*bbox_y) : std::nullopt),
    bbox_w_(bbox_w ? std::optional<int64_t>(*bbox_w) : std::nullopt),
    bbox_h_(bbox_h ? std::optional<int64_t>(*bbox_h) : std::nullopt),
    width_(width ? std::optional<int64_t>(*width) : std::nullopt),
    height_(height ? std::optional<int64_t>(*height) : std::nullopt),
    frame_count_(frame_count) {}

const std::string* FrameInfo::cam_idx() const {
  return cam_idx_ ? &(*cam_idx_) : nullptr;
}

void FrameInfo::set_cam_idx(const std::string_view* value_arg) {
  cam_idx_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void FrameInfo::set_cam_idx(std::string_view value_arg) {
  cam_idx_ = value_arg;
}


const std::string* FrameInfo::cam_num() const {
  return cam_num_ ? &(*cam_num_) : nullptr;
}

void FrameInfo::set_cam_num(const std::string_view* value_arg) {
  cam_num_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void FrameInfo::set_cam_num(std::string_view value_arg) {
  cam_num_ = value_arg;
}


const double* FrameInfo::brightness() const {
  return brightness_ ? &(*brightness_) : nullptr;
}

void FrameInfo::set_brightness(const double* value_arg) {
  brightness_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void FrameInfo::set_brightness(double value_arg) {
  brightness_ = value_arg;
}


const bool* FrameInfo::motion() const {
  return motion_ ? &(*motion_) : nullptr;
}

void FrameInfo::set_motion(const bool* value_arg) {
  motion_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void FrameInfo::set_motion(bool value_arg) {
  motion_ = value_arg;
}


const int64_t* FrameInfo::bbox_x() const {
  return bbox_x_ ? &(*bbox_x_) : nullptr;
}

void FrameInfo::set_bbox_x(const int64_t* value_arg) {
  bbox_x_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void FrameInfo::set_bbox_x(int64_t value_arg) {
  bbox_x_ = value_arg;
}


const int64_t* FrameInfo::bbox_y() const {
  return bbox_y_ ? &(*bbox_y_) : nullptr;
}

void FrameInfo::set_bbox_y(const int64_t* value_arg) {
  bbox_y_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void FrameInfo::set_bbox_y(int64_t value_arg) {
  bbox_y_ = value_arg;
}


const int64_t* FrameInfo::bbox_w() const {
  return bbox_w_ ? &(*bbox_w_) : nullptr;
}

void FrameInfo::set_bbox_w(const int64_t* value_arg) {
  bbox_w_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void FrameInfo::set_bbox_w(int64_t value_arg) {
  bbox_w_ = value_arg;
}


const int64_t* FrameInfo::bbox_h() const {
  return bbox_h_ ? &(*bbox_h_) : nullptr;
}

void FrameInfo::set_bbox_h(const int64_t* value_arg) {
  bbox_h_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void FrameInfo::set_bbox_h(int64_t value_arg) {
  bbox_h_ = value_arg;
}


const int64_t* FrameInfo::width() const {
  return width_ ? &(*width_) : nullptr;
}

void FrameInfo::set_width(const int64_t* value_arg) {
  width_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void FrameInfo::set_width(int64_t value_arg) {
  width_ = value_arg;
}


const int64_t* FrameInfo::height() const {
  return height_ ? &(*height_) : nullptr;
}

void FrameInfo::set_height(const int64_t* value_arg) {
  height_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void FrameInfo::set_height(int64_t value_arg) {
  height_ = value_arg;
}


int64_t FrameInfo::frame_count() const {
  return frame_count_;
}

void FrameInfo::set_frame_count(int64_t value_arg) {
  frame_count_ = value_arg;
}


EncodableList FrameInfo::ToEncodableList() const {
  EncodableList list;
  list.reserve(11);
  list.push_back(cam_idx_ ? EncodableValue(*cam_idx_) : EncodableValue());
  list.push_back(cam_num_ ? EncodableValue(*cam_num_) : EncodableValue());
  list.push_back(brightness_ ? EncodableValue(*brightness_) : EncodableValue());
  list.push_back(motion_ ? EncodableValue(*motion_) : EncodableValue());
  list.push_back(bbox_x_ ? EncodableValue(*bbox_x_) : EncodableValue());
  list.push_back(bbox_y_ ? EncodableValue(*bbox_y_) : EncodableValue());
  list.push_back(bbox_w_ ? EncodableValue(*bbox_w_) : EncodableValue());
  list.push_back(bbox_h_ ? EncodableValue(*bbox_h_) : EncodableValue());
  list.push_back(width_ ? EncodableValue(*width_) : EncodableValue());
  list.push_back(height_ ? EncodableValue(*height_) : EncodableValue());
  list.push_back(EncodableValue(frame_count_));
  return list;
}

FrameInfo FrameInfo::FromEncodableList(const EncodableList& list) {
  FrameInfo decoded(
    std::get<int64_t>(list[10]));
  auto& encodable_cam_idx = list[0];
  if (!encodable_cam_idx.IsNull()) {
    decoded.set_cam_idx(std::get<std::string>(encodable_cam_idx));
  }
  auto& encodable_cam_num = list[1];
  if (!encodable_cam_num.IsNull()) {
    decoded.set_cam_num(std::get<std::string>(encodable_cam_num));
  }
  auto& encodable_brightness = list[2];
  if (!encodable_brightness.IsNull()) {
    decoded.set_brightness(std::get<double>(encodable_brightness));
  }
  auto& encodable_motion = list[3];
  if (!encodable_motion.IsNull()) {
    decoded.set_motion(std::get<bool>(encodable_motion));
  }
  auto& encodable_bbox_x = list[4];
  if (!encodable_bbox_x.IsNull()) {
    decoded.set_bbox_x(std::get<int64_t>(encodable_bbox_x));
  }
  auto& encodable_bbox_y = list[5];
  if (!encodable_bbox_y.IsNull()) {
    decoded.set_bbox_y(std::get<int64_t>(encodable_bbox_y));
  }
  auto& encodable_bbox_w = list[6];
  if (!encodable_bbox_w.IsNull()) {
    decoded.set_bbox_w(std::get<int64_t>(encodable_bbox_w));
  }
  auto& encodable_bbox_h = list[7];
  if (!encodable_bbox_h.IsNull()) {
    decoded.set_bbox_h(std::get<int64_t>(encodable_bbox_h));
  }
  auto& encodable_width = list[8];
  if (!encodable_width.IsNull()) {
    decoded.set_width(std::get<int64_t>(encodable_width));
  }
  auto& encodable_height = list[9];
  if (!encodable_height.IsNull()) {
    decoded.set_height(std::get<int64_t>(encodable_height));
  }
  return decoded;
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        return CustomEncodableValue(FrameInfo::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(FrameInfo)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(std::any_cast<FrameInfo>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by NativeVideoHostApi.
const flutter::StandardMessageCodec& NativeVideoHostApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `NativeVideoHostApi` to handle messages through the `binary_messenger`.
void NativeVideoHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  NativeVideoHostApi* api) {
  NativeVideoHostApi::SetUp(binary_messenger, api, "");
}

void NativeVideoHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  NativeVideoHostApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.iscan_live_viewer.NativeVideoHostApi.initialize" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_key_arg = args.at(0);
          if (encodable_texture_key_arg.IsNull()) {
            reply(WrapError("texture_key_arg unexpectedly null."));
            return;
          }
          const int64_t texture_key_arg = encodable_texture_key_arg.LongValue();
          ErrorOr<int64_t> output = api->Initialize(texture_key_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.iscan_live_viewer.NativeVideoHostApi.startStream" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_key_arg = args.at(0);
          if (encodable_texture_key_arg.IsNull()) {
            reply(WrapError("texture_key_arg unexpectedly null."));
            return;
          }
          const int64_t texture_key_arg = encodable_texture_key_arg.LongValue();
          const auto& encodable_zmq_address_arg = args.at(1);
          if (encodable_zmq_address_arg.IsNull()) {
            reply(WrapError("zmq_address_arg unexpectedly null."));
            return;
          }
          const auto& zmq_address_arg = std::get<std::string>(encodable_zmq_address_arg);
          std::optional<FlutterError> output = api->StartStream(texture_key_arg, zmq_address_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.iscan_live_viewer.NativeVideoHostApi.stopStream" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_key_arg = args.at(0);
          if (encodable_texture_key_arg.IsNull()) {
            reply(WrapError("texture_key_arg unexpectedly null."));
            return;
          }
          const int64_t texture_key_arg = encodable_texture_key_arg.LongValue();
          std::optional<FlutterError> output = api->StopStream(texture_key_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.iscan_live_viewer.NativeVideoHostApi.getFrameInfo" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_key_arg = args.at(0);
          if (encodable_texture_key_arg.IsNull()) {
            reply(WrapError("texture_key_arg unexpectedly null."));
            return;
          }
          const int64_t texture_key_arg = encodable_texture_key_arg.LongValue();
          ErrorOr<std::optional<FrameInfo>> output = api->GetFrameInfo(texture_key_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          auto output_optional = std::move(output).TakeValue();
          if (output_optional) {
            wrapped.push_back(CustomEncodableValue(std::move(output_optional).value()));
          } else {
            wrapped.push_back(EncodableValue());
          }
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.iscan_live_viewer.NativeVideoHostApi.dispose" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_key_arg = args.at(0);
          if (encodable_texture_key_arg.IsNull()) {
            reply(WrapError("texture_key_arg unexpectedly null."));
            return;
          }
          const int64_t texture_key_arg = encodable_texture_key_arg.LongValue();
          std::optional<FlutterError> output = api->Dispose(texture_key_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue NativeVideoHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue NativeVideoHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

// Generated class from Pigeon that represents Flutter messages that can be called from C++.
NativeVideoFlutterApi::NativeVideoFlutterApi(flutter::BinaryMessenger* binary_messenger)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_("") {}

NativeVideoFlutterApi::NativeVideoFlutterApi(
  flutter::BinaryMessenger* binary_messenger,
  const std::string& message_channel_suffix)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_(message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "") {}

const flutter::StandardMessageCodec& NativeVideoFlutterApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

void NativeVideoFlutterApi::OnFrameReceived(
  const FrameInfo& info_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.iscan_live_viewer.NativeVideoFlutterApi.onFrameReceived" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    CustomEncodableValue(info_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void NativeVideoFlutterApi::OnError(
  const std::string& message_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.iscan_live_viewer.NativeVideoFlutterApi.onError" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    EncodableValue(message_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

